### ISSUE TITLE
无法在webview中使用吗？

### ISSUE THREAD

**Issue by goldencolor** [AlloyTeam/AlloyViewer#1]
基于webview的项目，页面是静态的在APP里面的无法使用吗？

**Comment by Caesor** [comment]
目前这个版本是基于react框架的，如果你的静态页面没有用react，我可以提供给你原生版本的js
发自网易邮箱大师
在2017年04月07日 11:50，goldencolor 写道： 基于webview的项目，页面是静态的在APP里面的无法使用吗？

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/AlloyTeam/AlloyViewer","title":"AlloyTeam/AlloyViewer","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/AlloyTeam/AlloyViewer"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"无法在webview中使用吗？ (#1)"}],"action":{"name":"View Issue","url":"https://github.com/AlloyTeam/AlloyViewer/issues/1"}}}

**Comment by goldencolor** [comment]
好的谢谢了，麻烦提供一个原生js 版本 lesn_333@qq.com

**Comment by goldencolor** [comment]
麻烦尽快下发呗@Caesor

**Comment by zhouyupeng** [comment]
求原生版js啊  zhou000888@foxmail.com  求发

**Comment by archi-git** [comment]
求原生archire@qq.com

**Comment by goldencolor** [comment]
@zhouyupeng @archi-git 你们收到了吗？

**Comment by goldencolor** [comment]
@Caesor 麻烦发下谢谢

**Comment by RongleCat** [comment]
@goldencolor 求原生版本 554348550@qq.com

**Comment by RongleCat** [comment]
@Caesor 求原生版本554348550@qq.com

**Comment by Caesor** [comment]
已经补充原生版本在 native 文件夹中
